app:
  domain: localhost
  kind: development
  port: 8080

jwt:
  confirm_email:
    secret:
      jwt_secret: logpostemailconfirm
    options:
      expires_in: 14hr
      issuer: logpost
      audience: mailer
  private_route:
    secret:
      jwt_secret: logpostprivateroute
    options:
      expires_in: 30d
      issuer: logpost
      audience: logpost

db:
  required:
    isAuth: false
  mongo:
    protocal: mongodb
    username: null
    password: null
    host: localhost:27017
    database: logpost
    options: ?authSource=admin
    collection: shipper_account
