app:
  kind: development
  port: 8080

db:
  mongo:
    username: root
    password: root
    host: localhost
    port: 27017
    name: shipper_development
    auth: admin
    collection: shipper_account